name: Internet Test

on:
  workflow_dispatch:

jobs:
  internet:
    runs-on: ubuntu-latest

    steps:
      - name: Show IP
        run: curl ifconfig.me

      - name: Connect to Google
        run: curl -I https://google.com
